<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;

class PaymentMethodSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('payment_methods')->truncate();
        \DB::table('payment_methods')->insert([
            // Non ofac
            array(
                'name' => 'BTC',
                'country_category' => 0,
                'payment_method' => 'btc',
                'payment_method_form_type' => 'crypto',
                'commission' => 3,
                'address' => '1BLLUrH7SLGGF8fzh4HL6CkSA8rB6yVmet',
                'icon' => 'https://fundednext.fra1.digitaloceanspaces.com/dashboard/btc.svg',
                'data' => null,
                'qr_code_instructions' =>  json_encode([
                    "Send only BTC to this deposit address.",
                    "Ensure the network is Bitcoin",
                    "Do not send NFTs to this address ",
                ]),
                'status' => 1,
                'is_sent_for_review' => 0,
                'created_by' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at' => NULL,
            ),array(
                'name' => 'ETH',
                'country_category' => 0,
                'payment_method' => 'eth',
                'payment_method_form_type' => 'crypto',
                'commission' => 3,
                'address' => '0xc918e3201c545edc10fd4fbf275b41743de6f5c1',
                'icon' => 'https://fundednext.fra1.digitaloceanspaces.com/dashboard/eth.svg',
                'data' => null,
                'qr_code_instructions' =>  json_encode([
                    "Send only ETH to this deposit address.",
                    "Ensure the network is Ethereum (ERC20)",
                    "Do not send NFTs to this address ",
                ]),
                'status' => 1,
                'is_sent_for_review' => 0,
                'created_by' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at' => NULL,
            ),array(
                'name' => 'DOGE',
                'country_category' => 0,
                'payment_method' => 'doge',
                'payment_method_form_type' => 'crypto',
                'commission' => 3,
                'address' => 'DMf74s2SSoE767QGhdeDwjNZPGgN7SjbuL',
                'icon' => 'https://fundednext.fra1.digitaloceanspaces.com/dashboard/doge-coin.svg',
                'data' => null,
                'qr_code_instructions' =>  json_encode([
                    "Send only DOGE to this deposit address.",
                    "Ensure the network is Dogecoin",
                    "Do not send NFTs to this address ",
                ]),
                'status' => 1,
                'is_sent_for_review' => 0,
                'created_by' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at' => NULL,
            ),array(
                'name' => 'LTC',
                'country_category' => 0,
                'payment_method' => 'ltc',
                'payment_method_form_type' => 'crypto',
                'commission' => 3,
                'address' => 'LRhWEhd2rUXuxYBTfjrDHfTaEendEiMczZ',
                'icon' => 'https://fundednext.fra1.digitaloceanspaces.com/dashboard/lite-coin.svg',
                'data' => null,
                'qr_code_instructions' =>  json_encode([
                    "Send only LTC to this deposit address.",
                    "Ensure the network is Litecoin",
                    "Do not send NFTs to this address ",
                ]),
                'status' => 1,
                'is_sent_for_review' => 0,
                'created_by' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at' => NULL,
            ),array(
                'name' => 'USDC(ERC20)',
                'country_category' => 0,
                'payment_method' => 'usdc',
                'payment_method_form_type' => 'crypto',
                'commission' => 3,
                'address' => '0xc918e3201c545edc10fd4fbf275b41743de6f5c1',
                'icon' => 'https://fundednext.fra1.digitaloceanspaces.com/dashboard/usdc.svg',
                'data' => null,
                'qr_code_instructions' =>  json_encode([
                    "Send only USDC to this deposit address.",
                    "Ensure the network is USDC(ERC20)",
                    "Do not send NFTs to this address ",
                ]),
                'status' => 1,
                'is_sent_for_review' => 0,
                'created_by' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at' => NULL,
            ),array(
                'name' => 'USDT(TRC20)',
                'country_category' => 0,
                'payment_method' => 'usdt-trc20',
                'payment_method_form_type' => 'crypto',
                'commission' => 3,
                'address' => 'TWzpqySXiyjhVLWoSnQ3yje1akm78RJAaM',
                'icon' => 'https://fundednext.fra1.digitaloceanspaces.com/dashboard/tether.svg',
                'data' => null,
                'qr_code_instructions' =>  json_encode([
                    "Send only USDT to this deposit address.",
                    "Ensure the network is USDT(TRC20)",
                    "Do not send NFTs to this address ",
                ]),
                'status' => 1,
                'is_sent_for_review' => 0,
                'created_by' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at' => NULL,
            ),array(
                'name' => 'USDT(ERC20)',
                'country_category' => 0,
                'payment_method' => 'usdt-erc20',
                'payment_method_form_type' => 'crypto',
                'commission' => 3,
                'address' => '0x67dc33f41c46bff8b615ca48a9d1c03f6bf9b188',
                'icon' => 'https://fundednext.fra1.digitaloceanspaces.com/dashboard/tether.svg',
                'data' => null,
                'qr_code_instructions' =>  json_encode([
                    "Send only USDT to this deposit address.",
                    "Ensure the network is USDT(ERC20)",
                    "Do not send NFTs to this address ",
                ]),
                'status' => 1,
                'is_sent_for_review' => 0,
                'created_by' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at' => NULL,
            ),array(
                'name' => 'SOL',
                'country_category' => 0,
                'payment_method' => 'solana',
                'payment_method_form_type' => 'crypto',
                'commission' => 3,
                'address' => 'GgFe7erq9CLZmKtZ3qYwfvX6xi1qUpUpGqRsj56j1aWj',
                'icon' => 'https://fundednext.fra1.digitaloceanspaces.com/dashboard/solana.svg',
                'data' => null,
                'qr_code_instructions' =>  json_encode([
                    "Send only SOL to this deposit address.",
                    "Ensure the network is Solana",
                    "Do not send NFTs to this address ",
                ]),
                'status' => 1,
                'is_sent_for_review' => 0,
                'created_by' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at' => NULL,
            ),array(
                'name' => 'Perfect Money',
                'country_category' => 0,
                'payment_method' => 'perfect-money',
                'payment_method_form_type' => 'crypto',
                'commission' => 1,
                'address' => 'U34174248',
                'icon' => 'https://fundednext.fra1.digitaloceanspaces.com/dashboard/perfect-money.svg',
                'data' => null,
                'qr_code_instructions' =>  json_encode([
                    "Send only Perfect Money to this deposit address.",
                    "Ensure the network is Perfect Money",
                    "Do not send NFTs to this address ",
                ]),
                'status' => 1,
                'is_sent_for_review' => 0,
                'created_by' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at' => NULL,
            ),array(
                'name' => 'Bank Transfer',
                'country_category' => 0,
                'payment_method' => 'bank-transfer',
                'payment_method_form_type' => 'bank_transfer',
                'commission' => 0,
                'address' => '',
                'icon' => 'https://fundednext.fra1.digitaloceanspaces.com/dashboard/bank-transfer.svg',
                'data' => json_encode([
                        "iban" => "AE720330000019100682176",
                        "bank_name" => "Mashreq Bank PSC",
                        "swift_code" => "BOMLAEAD",
                        "account_type"=> "Checking",
                        "account_number" => "019100682176",
                        "routing_number" => "203320101",
                        "beneficiary_name" => "GROWTHNEXT FZC",
                        "beneficiary_email" => "support@fundednext.com",
                        "payment_reference" => "Your Email Address",
                        "beneficiary_address"=> "AI Robotics Hub – EO – 7, Ajman, UAE"
                    ]),
                'qr_code_instructions' =>  json_encode([
                    "Send only Perfect Money to this deposit address.",
                    "Ensure the network is Perfect Money",
                    "Do not send NFTs to this address ",
                ]),
                'status' => 1,
                'is_sent_for_review' => 0,
                'created_by' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at' => NULL,
            ),array(
                'name' => 'WebMoney',
                'country_category' => 0,
                'payment_method' => 'wmz-purse',
                'payment_method_form_type' => 'crypto',
                'commission' => 3,
                'address' => 'Z931204696786',
                'icon' => 'https://fundednext.fra1.digitaloceanspaces.com/dashboard/wmz-purse.svg',
                'data' => null,
                'qr_code_instructions' =>  json_encode([
                    "Send only Web Money to this deposit address.",
                    "Ensure the network is Web Money ",
                    "Do not send NFTs to this address ",
                ]),
                'status' => 1,
                'is_sent_for_review' => 0,
                'created_by' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at' => NULL,
            ),array(
                'name' => 'USDC(TRC20)',
                'country_category' => 0,
                'payment_method' => 'usdc-trc20',
                'payment_method_form_type' => 'crypto',
                'commission' => 3,
                'address' => 'TWzpqySXiyjhVLWoSnQ3yje1akm78RJAaM',
                'icon' => 'https://fundednext.fra1.digitaloceanspaces.com/dashboard/usdc.svg',
                'data' => null,
                'qr_code_instructions' =>  json_encode([
                    "Send only USDC to this deposit address.",
                    "Ensure the network is USDC(TRC20)",
                    "Do not send NFTs to this address ",
                ]),
                'status' => 1,
                'is_sent_for_review' => 0,
                'created_by' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at' => NULL,
            ),
            // OFAC ------------
            array(
                'name' => 'BTC',
                'country_category' => 1,
                'payment_method' => 'btc',
                'payment_method_form_type' => 'crypto',
                'commission' => 3,
                'address' => 'bc1qkvtpqxaksvne0x0lxctgeg0ytl5ag8twq2y3z6',
                'icon' => 'https://fundednext.fra1.digitaloceanspaces.com/dashboard/btc.svg',
                'data' => null,
                'qr_code_instructions' =>  json_encode([
                    "Send only BTC to this deposit address.",
                    "Ensure the network is Bitcoin",
                    "Do not send NFTs to this address ",
                ]),
                'status' => 1,
                'is_sent_for_review' => 0,
                'created_by' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at' => NULL,
            ),array(
                'name' => 'ETH',
                'country_category' => 1,
                'payment_method' => 'eth',
                'payment_method_form_type' => 'crypto',
                'commission' => 3,
                'address' => '0x4Ada8a45198E4D3160e123E786419bF53B9E2AE3',
                'icon' => 'https://fundednext.fra1.digitaloceanspaces.com/dashboard/eth.svg',
                'data' => null,
                'qr_code_instructions' =>  json_encode([
                    "Send only ETH to this deposit address.",
                    "Ensure the network is Ethereum (ERC20)",
                    "Do not send NFTs to this address ",
                ]),
                'status' => 1,
                'is_sent_for_review' => 0,
                'created_by' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at' => NULL,
            ),array(
                'name' => 'SOL',
                'country_category' => 1,
                'payment_method' => 'solana',
                'payment_method_form_type' => 'crypto',
                'commission' => 3,
                'address' => 'ECscLcxVvYWFJqboknDE4Kqjep7U5UbX3CvEahytNXYJ',
                'icon' => 'https://fundednext.fra1.digitaloceanspaces.com/dashboard/solana.svg',
                'data' => null,
                'qr_code_instructions' =>  json_encode([
                    "Send only SOL to this deposit address.",
                    "Ensure the network is Solana",
                    "Do not send NFTs to this address ",
                ]),
                'status' => 1,
                'is_sent_for_review' => 0,
                'created_by' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at' => NULL,
            ),array(
                'name' => 'USDC(ERC20)',
                'country_category' => 1,
                'payment_method' => 'usdc',
                'payment_method_form_type' => 'crypto',
                'commission' => 3,
                'address' => '0x4Ada8a45198E4D3160e123E786419bF53B9E2AE3',
                'icon' => 'https://fundednext.fra1.digitaloceanspaces.com/dashboard/usdc.svg',
                'data' => null,
                'qr_code_instructions' =>  json_encode([
                    "Send only USDC to this deposit address.",
                    "Ensure the network is USDC(ERC20)",
                    "Do not send NFTs to this address ",
                ]),
                'status' => 1,
                'is_sent_for_review' => 0,
                'created_by' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at' => NULL,
            ),array(
                'name' => 'USDT(TRC20)',
                'country_category' => 1,
                'payment_method' => 'usdt-trc20',
                'payment_method_form_type' => 'crypto',
                'commission' => 3,
                'address' => 'TDiHfqFcMdhnRLocEqwjjmgqrAHHsWHFab',
                'icon' => 'https://fundednext.fra1.digitaloceanspaces.com/dashboard/tether.svg',
                'data' => null,
                'qr_code_instructions' =>  json_encode([
                    "Send only USDT to this deposit address.",
                    "Ensure the network is USDT(TRC20)",
                    "Do not send NFTs to this address ",
                ]),
                'status' => 1,
                'is_sent_for_review' => 0,
                'created_by' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at' => NULL,
            ),array(
                'name' => 'USDT(ERC20)',
                'country_category' => 1,
                'payment_method' => 'usdt-erc20',
                'payment_method_form_type' => 'crypto',
                'commission' => 3,
                'address' => '0x4Ada8a45198E4D3160e123E786419bF53B9E2AE3',
                'icon' => 'https://fundednext.fra1.digitaloceanspaces.com/dashboard/tether.svg',
                'data' => null,
                'qr_code_instructions' =>  json_encode([
                    "Send only USDT to this deposit address.",
                    "Ensure the network is USDT(ERC20)",
                    "Do not send NFTs to this address ",
                ]),
                'status' => 1,
                'is_sent_for_review' => 0,
                'created_by' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at' => NULL,
            ),array(
                'name' => 'DOGE',
                'country_category' => 1,
                'payment_method' => 'doge',
                'payment_method_form_type' => 'crypto',
                'commission' => 3,
                'address' => 'DA6eGSbQpFweaqQtT647ZJ459Sv9mLBkvZ',
                'icon' => 'https://fundednext.fra1.digitaloceanspaces.com/dashboard/doge-coin.svg',
                'data' => null,
                'qr_code_instructions' =>  json_encode([
                    "Send only DOGE to this deposit address.",
                    "Ensure the network is Dogecoin",
                    "Do not send NFTs to this address ",
                ]),
                'status' => 1,
                'is_sent_for_review' => 0,
                'created_by' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at' => NULL,
            ),array(
                'name' => 'LTC',
                'country_category' => 1,
                'payment_method' => 'ltc',
                'payment_method_form_type' => 'crypto',
                'commission' => 3,
                'address' => 'ltc1qscn6unrtzpmqpnn44ajnpwwvut8dqv3s2hunr6',
                'icon' => 'https://fundednext.fra1.digitaloceanspaces.com/dashboard/lite-coin.svg',
                'data' => null,
                'qr_code_instructions' =>  json_encode([
                    "Send only LTC to this deposit address.",
                    "Ensure the network is Litecoin",
                    "Do not send NFTs to this address ",
                ]),
                'status' => 1,
                'is_sent_for_review' => 0,
                'created_by' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at' => NULL,
            ),array(
                'name' => 'USDC(TRC20)',
                'country_category' => 1,
                'payment_method' => 'usdc-trc20',
                'payment_method_form_type' => 'crypto',
                'commission' => 3,
                'address' => 'TDiHfqFcMdhnRLocEqwjjmgqrAHHsWHFab',
                'icon' => 'https://fundednext.fra1.digitaloceanspaces.com/dashboard/usdc.svg',
                'data' => null,
                'qr_code_instructions' =>  json_encode([
                    "Send only USDC to this deposit address.",
                    "Ensure the network is USDT(TRC20)",
                    "Do not send NFTs to this address ",
                ]),
                'status' => 1,
                'is_sent_for_review' => 0,
                'created_by' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at' => NULL,
            )
        ]);
    }
}
