<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PlansTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('plans')->delete();
        
        \DB::table('plans')->insert(array (
            0 => 
            array (
                'id' => 1,
                'type' => 'Express Demo',
                'title' => 'Express Demo | 1M |15K',
                'description' => 'Express Demo 1 Month Period',
                'leverage' => 100,
                'startingBalance' => 15000,
                'duration' => '30',
                'next_plan' => 5,
                'new_account_on_next_plan' => 1,
                'created_at' => '2022-02-22 18:20:51',
                'updated_at' => '2022-02-22 18:20:51',
                'deleted_at' => NULL,
                'package_id' => 1,
                'server_id' => 1,
            ),
            1 => 
            array (
                'id' => 2,
                'type' => 'Express Demo',
                'title' => 'Express Demo | 1M |25K',
                'description' => 'Express Demo 1 Month Period',
                'leverage' => 100,
                'startingBalance' => 25000,
                'duration' => '30',
                'next_plan' => 5,
                'new_account_on_next_plan' => 1,
                'created_at' => '2022-02-22 18:20:51',
                'updated_at' => '2022-02-22 18:20:51',
                'deleted_at' => NULL,
                'package_id' => 1,
                'server_id' => 1,
            ),
            2 => 
            array (
                'id' => 3,
                'type' => 'Express Demo',
                'title' => 'Express Demo | 1M |50K',
                'description' => 'Express Demo 1 Month Period',
                'leverage' => 100,
                'startingBalance' => 50000,
                'duration' => '30',
                'next_plan' => 5,
                'new_account_on_next_plan' => 1,
                'created_at' => '2022-02-22 18:20:51',
                'updated_at' => '2022-02-22 18:20:51',
                'deleted_at' => NULL,
                'package_id' => 1,
                'server_id' => 1,
            ),
            3 => 
            array (
                'id' => 4,
                'type' => 'Express Demo',
                'title' => 'Express Demo | 1M |100K',
                'description' => 'Express Demo 1 Month Period',
                'leverage' => 100,
                'startingBalance' => 100000,
                'duration' => '30',
                'next_plan' => 5,
                'new_account_on_next_plan' => 1,
                'created_at' => '2022-02-22 18:20:51',
                'updated_at' => '2022-02-22 18:20:51',
                'deleted_at' => NULL,
                'package_id' => 1,
                'server_id' => 1,
            ),
            4 => 
            array (
                'id' => 5,
                'type' => 'Express Real',
                'title' => 'Express Real | 1M |15K',
                'description' => 'Express Real 1 Month Period',
                'leverage' => 100,
                'startingBalance' => 15000,
                'duration' => '30',
                'next_plan' => 5,
                'new_account_on_next_plan' => 0,
                'created_at' => '2022-02-22 18:20:51',
                'updated_at' => '2022-02-22 18:20:51',
                'deleted_at' => NULL,
                'package_id' => 1,
                'server_id' => 2,
            ),
            5 => 
            array (
                'id' => 6,
                'type' => 'Express Real',
                'title' => 'Express Real | 1M |25K',
                'description' => 'Express Real 1 Month Period',
                'leverage' => 100,
                'startingBalance' => 25000,
                'duration' => '30',
                'next_plan' => 6,
                'new_account_on_next_plan' => 0,
                'created_at' => '2022-02-22 18:20:51',
                'updated_at' => '2022-05-09 15:17:47',
                'deleted_at' => NULL,
                'package_id' => 1,
                'server_id' => 2,
            ),
            6 => 
            array (
                'id' => 7,
                'type' => 'Express Real',
                'title' => 'Express Real | 1M |50K',
                'description' => 'Express Real 1 Month Period',
                'leverage' => 100,
                'startingBalance' => 50000,
                'duration' => '30',
                'next_plan' => 7,
                'new_account_on_next_plan' => 0,
                'created_at' => '2022-02-22 18:20:51',
                'updated_at' => '2022-05-09 15:18:12',
                'deleted_at' => NULL,
                'package_id' => 1,
                'server_id' => 2,
            ),
            7 => 
            array (
                'id' => 8,
                'type' => 'Express Real',
                'title' => 'Express Real | 1M |100K',
                'description' => 'Express Real 1 Month Period',
                'leverage' => 100,
                'startingBalance' => 100000,
                'duration' => '30',
                'next_plan' => 8,
                'new_account_on_next_plan' => 0,
                'created_at' => '2022-02-22 18:20:51',
                'updated_at' => '2022-05-09 15:18:52',
                'deleted_at' => NULL,
                'package_id' => 1,
                'server_id' => 2,
            ),
            8 => 
            array (
                'id' => 9,
                'type' => 'Evaluation P1',
                'title' => 'Evaluation P1 | 1M |15K',
                'description' => 'Evaluation Demo 1 Month Period',
                'leverage' => 100,
                'startingBalance' => 15000,
                'duration' => '30',
                'next_plan' => 14,
                'new_account_on_next_plan' => 1,
                'created_at' => '2022-02-22 18:20:51',
                'updated_at' => '2022-02-22 18:20:51',
                'deleted_at' => NULL,
                'package_id' => 2,
                'server_id' => 1,
            ),
            9 => 
            array (
                'id' => 10,
                'type' => 'Evaluation P1',
                'title' => 'Evaluation P1 | 1M |25K',
                'description' => 'Evaluation Demo 1 Month Period',
                'leverage' => 100,
                'startingBalance' => 25000,
                'duration' => '30',
                'next_plan' => 15,
                'new_account_on_next_plan' => 1,
                'created_at' => '2022-02-22 18:20:51',
                'updated_at' => '2022-02-22 18:20:51',
                'deleted_at' => NULL,
                'package_id' => 2,
                'server_id' => 1,
            ),
            10 => 
            array (
                'id' => 11,
                'type' => 'Evaluation P1',
                'title' => 'Evaluation P1 | 1M |50K',
                'description' => 'Evaluation Demo 1 Month Period',
                'leverage' => 100,
                'startingBalance' => 50000,
                'duration' => '30',
                'next_plan' => 16,
                'new_account_on_next_plan' => 1,
                'created_at' => '2022-02-22 18:20:51',
                'updated_at' => '2022-02-22 18:20:51',
                'deleted_at' => NULL,
                'package_id' => 2,
                'server_id' => 1,
            ),
            11 => 
            array (
                'id' => 12,
                'type' => 'Evaluation P1',
                'title' => 'Evaluation P1|1M|100K',
                'description' => 'Evaluation Demo 1 Month Period',
                'leverage' => 100,
                'startingBalance' => 100000,
                'duration' => '30',
                'next_plan' => 17,
                'new_account_on_next_plan' => 1,
                'created_at' => '2022-02-22 18:20:51',
                'updated_at' => '2022-02-22 18:20:51',
                'deleted_at' => NULL,
                'package_id' => 2,
                'server_id' => 1,
            ),
            12 => 
            array (
                'id' => 13,
                'type' => 'Evaluation P1',
                'title' => 'Evaluation P1|1M|200K',
                'description' => 'Evaluation Demo 1 Month Period',
                'leverage' => 100,
                'startingBalance' => 200000,
                'duration' => '30',
                'next_plan' => 18,
                'new_account_on_next_plan' => 1,
                'created_at' => '2022-02-22 18:20:51',
                'updated_at' => '2022-02-22 18:20:51',
                'deleted_at' => NULL,
                'package_id' => 2,
                'server_id' => 1,
            ),
            13 => 
            array (
                'id' => 14,
                'type' => 'Evaluation P2',
                'title' => 'Evaluation P2|2M|15K',
                'description' => 'Evaluation Demo 2 Month Period',
                'leverage' => 100,
                'startingBalance' => 15000,
                'duration' => '60',
                'next_plan' => 19,
                'new_account_on_next_plan' => 1,
                'created_at' => '2022-02-22 18:20:51',
                'updated_at' => '2022-02-22 18:20:51',
                'deleted_at' => NULL,
                'package_id' => 2,
                'server_id' => 1,
            ),
            14 => 
            array (
                'id' => 15,
                'type' => 'Evaluation P2',
                'title' => 'Evaluation P2|2M|25K',
                'description' => 'Evaluation Demo 2 Month Period',
                'leverage' => 100,
                'startingBalance' => 25000,
                'duration' => '60',
                'next_plan' => 20,
                'new_account_on_next_plan' => 1,
                'created_at' => '2022-02-22 18:20:51',
                'updated_at' => '2022-02-22 18:20:51',
                'deleted_at' => NULL,
                'package_id' => 2,
                'server_id' => 1,
            ),
            15 => 
            array (
                'id' => 16,
                'type' => 'Evaluation P2',
                'title' => 'Evaluation P2|2M|50K',
                'description' => 'Evaluation Demo 2 Month Period',
                'leverage' => 100,
                'startingBalance' => 50000,
                'duration' => '60',
                'next_plan' => 21,
                'new_account_on_next_plan' => 1,
                'created_at' => '2022-02-22 18:20:51',
                'updated_at' => '2022-02-22 18:20:51',
                'deleted_at' => NULL,
                'package_id' => 2,
                'server_id' => 1,
            ),
            16 => 
            array (
                'id' => 17,
                'type' => 'Evaluation P2',
                'title' => 'Evaluation P2|2M|100K',
                'description' => 'Evaluation Demo 2 Month Period',
                'leverage' => 100,
                'startingBalance' => 100000,
                'duration' => '60',
                'next_plan' => 22,
                'new_account_on_next_plan' => 1,
                'created_at' => '2022-02-22 18:20:51',
                'updated_at' => '2022-02-22 18:20:51',
                'deleted_at' => NULL,
                'package_id' => 2,
                'server_id' => 1,
            ),
            17 => 
            array (
                'id' => 18,
                'type' => 'Evaluation P2',
                'title' => 'Evaluation P2|2M|200K',
                'description' => 'Evaluation Demo 2 Month Period',
                'leverage' => 100,
                'startingBalance' => 200000,
                'duration' => '60',
                'next_plan' => 23,
                'new_account_on_next_plan' => 1,
                'created_at' => '2022-02-22 18:20:51',
                'updated_at' => '2022-02-22 18:20:51',
                'deleted_at' => NULL,
                'package_id' => 2,
                'server_id' => 1,
            ),
            18 => 
            array (
                'id' => 19,
                'type' => 'Evaluation Real',
                'title' => 'Evaluation Real|1M|15K',
                'description' => 'Evaluation Real 30 Period',
                'leverage' => 100,
                'startingBalance' => 15000,
                'duration' => '15',
                'next_plan' => 19,
                'new_account_on_next_plan' => 0,
                'created_at' => '2022-02-22 18:20:51',
                'updated_at' => '2022-05-09 15:08:39',
                'deleted_at' => NULL,
                'package_id' => 2,
                'server_id' => 2,
            ),
            19 => 
            array (
                'id' => 20,
                'type' => 'Evaluation Real',
                'title' => 'Evaluation Real|1M|25K',
                'description' => 'Evaluation Real 30 Period',
                'leverage' => 100,
                'startingBalance' => 25000,
                'duration' => '15',
                'next_plan' => 20,
                'new_account_on_next_plan' => 0,
                'created_at' => '2022-02-22 18:20:51',
                'updated_at' => '2022-05-09 15:12:55',
                'deleted_at' => NULL,
                'package_id' => 2,
                'server_id' => 2,
            ),
            20 => 
            array (
                'id' => 21,
                'type' => 'Evaluation Real',
                'title' => 'Evaluation Real|1M|50K',
                'description' => 'Evaluation Real 30 Period',
                'leverage' => 100,
                'startingBalance' => 50000,
                'duration' => '15',
                'next_plan' => 21,
                'new_account_on_next_plan' => 0,
                'created_at' => '2022-02-22 18:20:51',
                'updated_at' => '2022-05-09 15:13:13',
                'deleted_at' => NULL,
                'package_id' => 2,
                'server_id' => 2,
            ),
            21 => 
            array (
                'id' => 22,
                'type' => 'Evaluation Real',
                'title' => 'Evaluation Real|1M|100K',
                'description' => 'Evaluation Real 30 Period',
                'leverage' => 100,
                'startingBalance' => 100000,
                'duration' => '15',
                'next_plan' => 22,
                'new_account_on_next_plan' => 0,
                'created_at' => '2022-02-22 18:20:51',
                'updated_at' => '2022-05-09 15:13:26',
                'deleted_at' => NULL,
                'package_id' => 2,
                'server_id' => 2,
            ),
            22 => 
            array (
                'id' => 23,
                'type' => 'Evaluation Real',
                'title' => 'Evaluation Real|1M|200K',
                'description' => 'Evaluation Real 30 Period',
                'leverage' => 100,
                'startingBalance' => 200000,
                'duration' => '15',
                'next_plan' => 23,
                'new_account_on_next_plan' => 0,
                'created_at' => '2022-02-22 18:20:51',
                'updated_at' => '2022-05-09 15:13:36',
                'deleted_at' => NULL,
                'package_id' => 2,
                'server_id' => 2,
            ),
            23 => 
            array (
                'id' => 24,
                'type' => 'Express Demo',
                'title' => 'Express Demo | 1Month |15K',
                'description' => 'Express Demo 1 Month Period',
                'leverage' => 100,
                'startingBalance' => 15000,
                'duration' => '30',
                'next_plan' => 5,
                'new_account_on_next_plan' => 1,
                'created_at' => '2022-02-22 18:20:51',
                'updated_at' => '2022-02-22 18:20:51',
                'deleted_at' => NULL,
                'package_id' => 1,
                'server_id' => 3,
            ),
            24 => 
            array (
                'id' => 25,
                'type' => 'Express Demo',
                'title' => 'Express Demo | 1Month |25K',
                'description' => 'Express Demo 1 Month Period',
                'leverage' => 100,
                'startingBalance' => 25000,
                'duration' => '30',
                'next_plan' => 5,
                'new_account_on_next_plan' => 1,
                'created_at' => '2022-02-22 18:20:51',
                'updated_at' => '2022-02-22 18:20:51',
                'deleted_at' => NULL,
                'package_id' => 1,
                'server_id' => 3,
            ),
            25 => 
            array (
                'id' => 26,
                'type' => 'Express Demo',
                'title' => 'Express Demo | 1Month |50K',
                'description' => 'Express Demo 1 Month Period',
                'leverage' => 100,
                'startingBalance' => 50000,
                'duration' => '30',
                'next_plan' => 5,
                'new_account_on_next_plan' => 1,
                'created_at' => '2022-02-22 18:20:51',
                'updated_at' => '2022-02-22 18:20:51',
                'deleted_at' => NULL,
                'package_id' => 1,
                'server_id' => 3,
            ),
            26 => 
            array (
                'id' => 27,
                'type' => 'Express Demo',
                'title' => 'Express Demo | 1Month |100K',
                'description' => 'Express Demo 1 Month Period',
                'leverage' => 100,
                'startingBalance' => 100000,
                'duration' => '30',
                'next_plan' => 5,
                'new_account_on_next_plan' => 1,
                'created_at' => '2022-02-22 18:20:51',
                'updated_at' => '2022-02-22 18:20:51',
                'deleted_at' => NULL,
                'package_id' => 1,
                'server_id' => 3,
            ),
            27 => 
            array (
                'id' => 28,
                'type' => 'Evaluation P1',
                'title' => 'Evaluation P1 | 1Month |15K',
                'description' => 'Evaluation Demo 1 Month Period',
                'leverage' => 100,
                'startingBalance' => 15000,
                'duration' => '30',
                'next_plan' => 33,
                'new_account_on_next_plan' => 1,
                'created_at' => '2022-02-22 18:20:51',
                'updated_at' => '2022-02-22 18:20:51',
                'deleted_at' => NULL,
                'package_id' => 2,
                'server_id' => 3,
            ),
            28 => 
            array (
                'id' => 29,
                'type' => 'Evaluation P1',
                'title' => 'Evaluation P1 | 1Month |25K',
                'description' => 'Evaluation Demo 1 Month Period',
                'leverage' => 100,
                'startingBalance' => 25000,
                'duration' => '30',
                'next_plan' => 34,
                'new_account_on_next_plan' => 1,
                'created_at' => '2022-02-22 18:20:51',
                'updated_at' => '2022-02-22 18:20:51',
                'deleted_at' => NULL,
                'package_id' => 2,
                'server_id' => 3,
            ),
            29 => 
            array (
                'id' => 30,
                'type' => 'Evaluation P1',
                'title' => 'Evaluation P1 | 1Month |50K',
                'description' => 'Evaluation Demo 1 Month Period',
                'leverage' => 100,
                'startingBalance' => 50000,
                'duration' => '30',
                'next_plan' => 35,
                'new_account_on_next_plan' => 1,
                'created_at' => '2022-02-22 18:20:51',
                'updated_at' => '2022-02-22 18:20:51',
                'deleted_at' => NULL,
                'package_id' => 2,
                'server_id' => 3,
            ),
            30 => 
            array (
                'id' => 31,
                'type' => 'Evaluation P1',
                'title' => 'Evaluation P1|1Month|100K',
                'description' => 'Evaluation Demo 1 Month Period',
                'leverage' => 100,
                'startingBalance' => 100000,
                'duration' => '30',
                'next_plan' => 36,
                'new_account_on_next_plan' => 1,
                'created_at' => '2022-02-22 18:20:51',
                'updated_at' => '2022-02-22 18:20:51',
                'deleted_at' => NULL,
                'package_id' => 2,
                'server_id' => 3,
            ),
            31 => 
            array (
                'id' => 32,
                'type' => 'Evaluation P1',
                'title' => 'Evaluation P1|1Month|200K',
                'description' => 'Evaluation Demo 1 Month Period',
                'leverage' => 100,
                'startingBalance' => 200000,
                'duration' => '30',
                'next_plan' => 37,
                'new_account_on_next_plan' => 1,
                'created_at' => '2022-02-22 18:20:51',
                'updated_at' => '2022-02-22 18:20:51',
                'deleted_at' => NULL,
                'package_id' => 2,
                'server_id' => 3,
            ),
            32 => 
            array (
                'id' => 33,
                'type' => 'Evaluation P2',
                'title' => 'Evaluation P2|2Month|15K',
                'description' => 'Evaluation Demo 2 Month Period',
                'leverage' => 100,
                'startingBalance' => 15000,
                'duration' => '60',
                'next_plan' => 19,
                'new_account_on_next_plan' => 1,
                'created_at' => '2022-02-22 18:20:51',
                'updated_at' => '2022-02-22 18:20:51',
                'deleted_at' => NULL,
                'package_id' => 2,
                'server_id' => 3,
            ),
            33 => 
            array (
                'id' => 34,
                'type' => 'Evaluation P2',
                'title' => 'Evaluation P2|2Month|25K',
                'description' => 'Evaluation Demo 2 Month Period',
                'leverage' => 100,
                'startingBalance' => 25000,
                'duration' => '60',
                'next_plan' => 20,
                'new_account_on_next_plan' => 1,
                'created_at' => '2022-02-22 18:20:51',
                'updated_at' => '2022-02-22 18:20:51',
                'deleted_at' => NULL,
                'package_id' => 2,
                'server_id' => 3,
            ),
            34 => 
            array (
                'id' => 35,
                'type' => 'Evaluation P2',
                'title' => 'Evaluation P2|2Month|50K',
                'description' => 'Evaluation Demo 2 Month Period',
                'leverage' => 100,
                'startingBalance' => 50000,
                'duration' => '60',
                'next_plan' => 21,
                'new_account_on_next_plan' => 1,
                'created_at' => '2022-02-22 18:20:51',
                'updated_at' => '2022-02-22 18:20:51',
                'deleted_at' => NULL,
                'package_id' => 2,
                'server_id' => 3,
            ),
            35 => 
            array (
                'id' => 36,
                'type' => 'Evaluation P2',
                'title' => 'Evaluation P2|2Month|100K',
                'description' => 'Evaluation Demo 2 Month Period',
                'leverage' => 100,
                'startingBalance' => 100000,
                'duration' => '60',
                'next_plan' => 22,
                'new_account_on_next_plan' => 1,
                'created_at' => '2022-02-22 18:20:51',
                'updated_at' => '2022-02-22 18:20:51',
                'deleted_at' => NULL,
                'package_id' => 2,
                'server_id' => 3,
            ),
            36 => 
            array (
                'id' => 37,
                'type' => 'Evaluation P2',
                'title' => 'Evaluation P2|2Month|200K',
                'description' => 'Evaluation Demo 2 Month Period',
                'leverage' => 100,
                'startingBalance' => 200000,
                'duration' => '60',
                'next_plan' => 23,
                'new_account_on_next_plan' => 1,
                'created_at' => '2022-02-22 18:20:51',
                'updated_at' => '2022-02-22 18:20:51',
                'deleted_at' => NULL,
                'package_id' => 2,
                'server_id' => 3,
            ),
            37 => 
            array (
                'id' => 38,
                'type' => 'Express Real',
                'title' => 'Express Real | 1Month |15K',
                'description' => 'Express Real 1 Month Period',
                'leverage' => 100,
                'startingBalance' => 15000,
                'duration' => '30',
                'next_plan' => 5,
                'new_account_on_next_plan' => 0,
                'created_at' => '2022-02-22 18:20:51',
                'updated_at' => '2022-02-22 18:20:51',
                'deleted_at' => NULL,
                'package_id' => 1,
                'server_id' => 4,
            ),
            38 => 
            array (
                'id' => 39,
                'type' => 'Express Real',
                'title' => 'Express Real | 1Month |25K',
                'description' => 'Express Real 1 Month Period',
                'leverage' => 100,
                'startingBalance' => 25000,
                'duration' => '30',
                'next_plan' => 6,
                'new_account_on_next_plan' => 0,
                'created_at' => '2022-02-22 18:20:51',
                'updated_at' => '2022-05-09 15:17:47',
                'deleted_at' => NULL,
                'package_id' => 1,
                'server_id' => 4,
            ),
            39 => 
            array (
                'id' => 40,
                'type' => 'Express Real',
                'title' => 'Express Real | 1Month |50K',
                'description' => 'Express Real 1 Month Period',
                'leverage' => 100,
                'startingBalance' => 50000,
                'duration' => '30',
                'next_plan' => 7,
                'new_account_on_next_plan' => 0,
                'created_at' => '2022-02-22 18:20:51',
                'updated_at' => '2022-05-09 15:18:12',
                'deleted_at' => NULL,
                'package_id' => 1,
                'server_id' => 4,
            ),
            40 => 
            array (
                'id' => 41,
                'type' => 'Express Real',
                'title' => 'Express Real | 1Month |100K',
                'description' => 'Express Real 1 Month Period',
                'leverage' => 100,
                'startingBalance' => 100000,
                'duration' => '30',
                'next_plan' => 8,
                'new_account_on_next_plan' => 0,
                'created_at' => '2022-02-22 18:20:51',
                'updated_at' => '2022-05-09 15:18:52',
                'deleted_at' => NULL,
                'package_id' => 1,
                'server_id' => 4,
            ),
            41 => 
            array (
                'id' => 42,
                'type' => 'Evaluation Real',
                'title' => 'Evaluation Real|1Month|15K',
                'description' => 'Evaluation Real 30 Period',
                'leverage' => 100,
                'startingBalance' => 15000,
                'duration' => '15',
                'next_plan' => 19,
                'new_account_on_next_plan' => 0,
                'created_at' => '2022-02-22 18:20:51',
                'updated_at' => '2022-05-09 15:08:39',
                'deleted_at' => NULL,
                'package_id' => 2,
                'server_id' => 4,
            ),
            42 => 
            array (
                'id' => 43,
                'type' => 'Evaluation Real',
                'title' => 'Evaluation Real|1Month|25K',
                'description' => 'Evaluation Real 30 Period',
                'leverage' => 100,
                'startingBalance' => 25000,
                'duration' => '15',
                'next_plan' => 20,
                'new_account_on_next_plan' => 0,
                'created_at' => '2022-02-22 18:20:51',
                'updated_at' => '2022-05-09 15:12:55',
                'deleted_at' => NULL,
                'package_id' => 2,
                'server_id' => 4,
            ),
            43 => 
            array (
                'id' => 44,
                'type' => 'Evaluation Real',
                'title' => 'Evaluation Real|1Month|50K',
                'description' => 'Evaluation Real 30 Period',
                'leverage' => 100,
                'startingBalance' => 50000,
                'duration' => '15',
                'next_plan' => 21,
                'new_account_on_next_plan' => 0,
                'created_at' => '2022-02-22 18:20:51',
                'updated_at' => '2022-05-09 15:13:13',
                'deleted_at' => NULL,
                'package_id' => 2,
                'server_id' => 4,
            ),
            44 => 
            array (
                'id' => 45,
                'type' => 'Evaluation Real',
                'title' => 'Evaluation Real|1Month|100K',
                'description' => 'Evaluation Real 30 Period',
                'leverage' => 100,
                'startingBalance' => 100000,
                'duration' => '15',
                'next_plan' => 22,
                'new_account_on_next_plan' => 0,
                'created_at' => '2022-02-22 18:20:51',
                'updated_at' => '2022-05-09 15:13:26',
                'deleted_at' => NULL,
                'package_id' => 2,
                'server_id' => 4,
            ),
            45 => 
            array (
                'id' => 46,
                'type' => 'Evaluation Real',
                'title' => 'Evaluation Real|1Month|200K',
                'description' => 'Evaluation Real 30 Period',
                'leverage' => 100,
                'startingBalance' => 200000,
                'duration' => '15',
                'next_plan' => 23,
                'new_account_on_next_plan' => 0,
                'created_at' => '2022-02-22 18:20:51',
                'updated_at' => '2022-05-09 15:13:36',
                'deleted_at' => NULL,
                'package_id' => 2,
                'server_id' => 4,
            ),
        ));
        
        
    }
}