<?php

return [
    'SUPERVISOR_QUEUE_BREACH_EVENT_JOB_ENABLED' => env('SUPERVISOR_QUEUE_BREACH_EVENT_JOB_ENABLED', true),
    'SUPERVISOR_QUEUE_BREACH_EVENT_JOB_MIN_PROCESS' => env('SUPERVISOR_QUEUE_BREACH_EVENT_JOB_MIN_PROCESS', 1),
    'SUPERVISOR_QUEUE_BREACH_EVENT_JOB_MAX_PROCESS' => env('SUPERVISOR_QUEUE_BREACH_EVENT_JOB_MAX_PROCESS', 8),

    'SUPERVISOR_QUEUE_ON_BREACH_NOTIFY_USER_JOB_ENABLED' => env('SUPERVISOR_QUEUE_ON_BREACH_NOTIFY_USER_JOB_ENABLED', true),
    'SUPERVISOR_QUEUE_ON_BREACH_NOTIFY_USER_JOB_MIN_PROCESS' => env('SUPERVISOR_QUEUE_ON_BREACH_NOTIFY_USER_JOB_MIN_PROCESS', 1),
    'SUPERVISOR_QUEUE_ON_BREACH_NOTIFY_USER_JOB_MAX_PROCESS' => env('SUPERVISOR_QUEUE_ON_BREACH_NOTIFY_USER_JOB_MAX_PROCESS', 3),

    'SUPERVISOR_QUEUE_DEFAULT_JOB_ENABLED' => env('SUPERVISOR_QUEUE_DEFAULT_JOB_ENABLED', true),
    'SUPERVISOR_QUEUE_DEFAULT_JOB_MIN_PROCESS' => env('SUPERVISOR_QUEUE_DEFAULT_JOB_MIN_PROCESS', 1),
    'SUPERVISOR_QUEUE_DEFAULT_JOB_MAX_PROCESS' => env('SUPERVISOR_QUEUE_DEFAULT_JOB_MAX_PROCESS', 3),

    'SUPERVISOR_QUEUE_TRADE_SYNC_JOB_ENABLED' => env('SUPERVISOR_QUEUE_TRADE_SYNC_JOB_ENABLED', true),
    'SUPERVISOR_QUEUE_TRADE_SYNC_JOB_MIN_PROCESS' => env('SUPERVISOR_QUEUE_TRADE_SYNC_JOB_MIN_PROCESS', 1),
    'SUPERVISOR_QUEUE_TRADE_SYNC_JOB_MAX_PROCESS' => env('SUPERVISOR_QUEUE_TRADE_SYNC_JOB_MAX_PROCESS', 3),

    'SUPERVISOR_QUEUE_TRADE_CLOSE_JOB_ENABLED' => env('SUPERVISOR_QUEUE_TRADE_CLOSE_JOB_ENABLED', true),
    'SUPERVISOR_QUEUE_TRADE_CLOSE_JOB_MIN_PROCESS' => env('SUPERVISOR_QUEUE_TRADE_CLOSE_JOB_MIN_PROCESS', 1),
    'SUPERVISOR_QUEUE_TRADE_CLOSE_JOB_MAX_PROCESS' => env('SUPERVISOR_QUEUE_TRADE_CLOSE_JOB_MAX_PROCESS', 3),

    'SUPERVISOR_QUEUE_TRADE_CLOSE_EVENT_JOB_ENABLED' => env('SUPERVISOR_QUEUE_TRADE_CLOSE_EVENT_JOB_ENABLED', true),
    'SUPERVISOR_QUEUE_TRADE_CLOSE_EVENT_JOB_MIN_PROCESS' => env('SUPERVISOR_QUEUE_TRADE_CLOSE_EVENT_JOB_MIN_PROCESS', 1),
    'SUPERVISOR_QUEUE_TRADE_CLOSE_EVENT_JOB_MAX_PROCESS' => env('SUPERVISOR_QUEUE_TRADE_CLOSE_EVENT_JOB_MAX_PROCESS', 3),

    'SUPERVISOR_QUEUE_PROFIT_CHECKER_JOB_ENABLED' => env('SUPERVISOR_QUEUE_PROFIT_CHECKER_JOB_ENABLED', true),
    'SUPERVISOR_QUEUE_PROFIT_CHECKER_JOB_MIN_PROCESS' => env('SUPERVISOR_QUEUE_PROFIT_CHECKER_JOB_MIN_PROCESS', 1),
    'SUPERVISOR_QUEUE_PROFIT_CHECKER_JOB_MAX_PROCESS' => env('SUPERVISOR_QUEUE_PROFIT_CHECKER_JOB_MAX_PROCESS', 3),

    'SUPERVISOR_QUEUE_DISCORD_ALERT_JOB_ENABLED' => env('SUPERVISOR_QUEUE_DISCORD_ALERT_JOB_ENABLED', true),
    'SUPERVISOR_QUEUE_DISCORD_ALERT_JOB_MIN_PROCESS' => env('SUPERVISOR_QUEUE_DISCORD_ALERT_JOB_MIN_PROCESS', 1),
    'SUPERVISOR_QUEUE_DISCORD_ALERT_JOB_MAX_PROCESS' => env('SUPERVISOR_QUEUE_DISCORD_ALERT_JOB_MAX_PROCESS', 3),

];
